- name: "Installation SNMP"
  hosts: linux
  remote_user: root

  tasks:
  - name: "Installation du paquet snmpd"
    yum: 
      name:
        - net-snmp*
        - epel-release*
      state: "latest"
    async: 3600
    poll: 0
    register: yum_sleeper

  - name: "ouverture des ports du firewall 1/3"
    firewalld:
      service: snmpd
      zone: public
      immediate: yes
      permanent: true
      state: enabled

  - name: "ouverture des ports du firewall 2/3"
    firewalld:
      port: 161-162/udp
      zone: public
      immediate: yes
      permanent: true
      state: enabled
   
  - name: "ouverture des ports du firewall 3/3"
    firewalld:
      port: 161-162/tcp
      zone: public
      immediate: yes
      permanent: true
      state: enabled
      
  - name: "Mise en place de la Template snmpd.conf"
    template:
      src: "/opt/ansible/files/snmp/etc-snmp-snmpd.conf"
      dest: "/etc/snmp/snmpd.conf"
      owner: "root"
      group: "root"
      mode: "755"
      backup: "yes"
    notify: Restart snmpd

  - name: "Activation du service snmpd"
    service:
      name: snmpd
      enabled: yes
      state: started

  handlers:
  - name: Restart snmpd
    service:
      name: "snmpd"
      state: "restarted"