---
- name: Arret des serveurs
  hosts: windows
  gather_facts: no
  become: false
  
  tasks:
  - name: Turn off computers
#    raw: Stop-Computer –computer {{ ansible_hostname }} –Credential ictadmin
    raw: shutdown /s /hybrid /t 15 /c "We are turning computers off after maintenance"
...