---
- name: "Installation Hyper-V"
  hosts: windows
  gather_facts: no
  become: false


  tasks:
    - name: "Installation du composant Hyper-V"
      win_feature:
        name: 
        - Hyper-V
        include_sub_features: yes
        include_management_tools: yes
        state: present
      register: win_feature
...