---
- name: "Parametrage firewall"
  hosts: windows
  gather_facts: no
  become: false
  
  tasks:
  - name: Open firewall port 80 for the IIS web server on {{ inventory_hostname }}
        win_firewall_rule:
        name: "{{ inventory_hostname }}_80"
        enable: yes
        state: present
        localport: 80
        action: Allow
        direction: In
        protocol: Tcp
...