---
- name: Installation SNMP
  hosts: windows
  gather_facts: no
  become: false

  tasks:
    - name: "Installation du composant SNMP"
      win_feature:
        name: 
        - SNMP-Service
        - SNMP-WMI-Provider
        include_sub_features: yes
        include_management_tools: yes
        state: present
      register: win_feature
    
    - name: Remplacement de la communaute SNMP
      win_snmp:
        community_strings:
          - EXEMPLE-PRIV
          - EXEMPLE-PUB
        permitted_managers:
          - 10.59.1.11
        action: set
...