---
- name: "Installation SNMP"
  hosts: WIN-QAR8IEP0187
  gather_facts: no
  become: false

  tasks:
    - name: "Installation du composant SNMP"
      win_feature:
        name: 
        - SNMP-Service
        - SNMP-WMI-Provider
        include_sub_features: yes
        include_management_tools: yes
        state: present
      register: win_feature
    
    - name: Replace SNMP communities and managers
      win_snmp:
        community_strings:
          - FICHORGA-PRIV
          - FICHORGA-PUB
        permitted_managers:
          - 120.4.0.71
        action: set
...